### ISSUE TITLE
Webhooks do not work properly in the new version of Grafana (v9.3.x).

### ISSUE THREAD

**Issue by jihyungSong** [cloudforet-io/plugin-grafana-mon-webhook#1]
After upgrading Grafana to v9.3.x, a parse error occurs when sending webhooks.
A webhook data format is different from the previous version.

**Comment by jihyungSong** [comment]
```
2023-01-10T07:56:19.225Z [INFO] tnx-16aeb4a5ca9e Event.parse (service.py:75) (REQUEST) => {"options": {}, "data": {"orgId": 1.0, "externalURL": "https://grafana.stargate.cloudeco.io/", "commonLabels": {"alertname": "TestAlert", "instance": "Grafana"}, "commonAnnotations": {"summary": "Notification test"}, "groupKey": "{alertname=\"TestAlert\", instance=\"Grafana\"}2023-01-10 07:56:19.168474598 +0000 UTC m=+17860.972597770", "message": "**Firing**\n\nValue: [no value]\nLabels:\n - alertname = TestAlert\n - instance = Grafana\nAnnotations:\n - summary = Notification test\nSilence: https://grafana.stargate.cloudeco.io/alerting/silence/new?alertmanager=grafana&matcher=alertname%3DTestAlert&matcher=instance%3DGrafana\n", "receiver": "", "status": "firing", "version": "1", "alerts": [{"values": null, "endsAt": "0001-01-01T00:00:00Z", "annotations": {"summary": "Notification test"}, "generatorURL": "", "silenceURL": "https://grafana.stargate.cloudeco.io/alerting/silence/new?alertmanager=grafana&matcher=alertname%3DTestAlert&matcher=instance%3DGrafana", "labels": {"alertname": "TestAlert", "instance": "Grafana"}, "status": "firing", "panelURL": "", "startsAt": "2023-01-10T07:56:19.168474598Z", "valueString": "[ metric='foo' labels={instance=bar} value=10 ]", "dashboardURL": "", "fingerprint": "57c6d9296de2ad39"}], "truncatedAlerts": 0.0, "state": "alerting", "title": "[FIRING:1]  (TestAlert Grafana)", "groupLabels": {}}}
2023-01-10T07:56:19.226Z [ERROR] tnx-16aeb4a5ca9e Event.parse (service.py:146) (Error) => Required field is missing(field= dashboard_id)
	error_code = ERROR_REQUIRED_FIELDS
	status_code = INTERNAL
	message = Required field is missing(field= dashboard_id)  Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/grpc_grafana_monitoring_webhook-1.0-py3.8.egg/spaceone/monitoring/interface/grpc/event.py", line 14, in parse
    return self.locator.get_info('EventsInfo', event_service.parse(params))
  File "/usr/local/lib/python3.8/site-packages/spaceone/core/service/service.py", line 58, in wrapped_func
    return _pipeline(func, self, params, append_meta)
  File "/usr/local/lib/python3.8/site-packages/spaceone/core/service/service.py", line 121, in _pipeline
    raise e
  File "/usr/local/lib/python3.8/site-packages/spaceone/core/service/service.py", line 107, in _pipeline
    response_or_iterator = func(self, params)
  File "/usr/local/lib/python3.8/site-packages/spaceone/core/service/utils.py", line 41, in wrapped_func
    return func(cls, params)
  File "/usr/local/lib/python3.8/site-packages/grpc_grafana_monitoring_webhook-1.0-py3.8.egg/spaceone/monitoring/service/event_service.py", line 32, in parse
    parsed_event = self.event_mgr.parse(raw_data)
  File "/usr/local/lib/python3.8/site-packages/grpc_grafana_monitoring_webhook-1.0-py3.8.egg/spaceone/monitoring/manager/event_manager.py", line 22, in parse
    event_key = self._generate_event_key(raw_data)
  File "/usr/local/lib/python3.8/site-packages/grpc_grafana_monitoring_webhook-1.0-py3.8.egg/spaceone/monitoring/manager/event_manager.py", line 57, in _generate_event_key
    raise ERROR_REQUIRED_FIELDS(field='dashboard_id')
spaceone.monitoring.error.event.ERROR_REQUIRED_FIELDS:
	error_code = ERROR_REQUIRED_FIELDS
	status_code = INTERNAL
	message = Required field is missing(field= dashboard_id)
```

**Comment by gikang82** [comment]
Hello,
Thank you for your report.
It will be resolved in latest plugin release as below
https://github.com/cloudforet-io/plugin-grafana-mon-webhook/commit/b5bccc7fa0a883f80c661af6041a09a3e3a7fcdf
